apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-models
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: NFS_SERVER
    path: /mnt/nas/models
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-models
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-models
  resources:
    requests:
      storage: 1000Gi
